version: 0.2

phases:
  install:
    commands:
      - apt update && apt install -y docker.io
      - nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 &
      - timeout 30 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - docker build -t app .
  build:
    commands:
      - docker images
      - docker run app echo "Hello, World!"
      - docker inspect app -f '{{ .Architecture }}'
